### ISSUE TITLE
is there any typescript version of this package is available ??

### ISSUE THREAD

**Issue by ghulamhussain** [roderickhsiao/react-aspect-ratio#1]
i am having an error . Could not find a declaration file for module 'react-aspect-ratio'.

**Comment by roderickhsiao** [comment]
Thanks for reaching out, we didn't create the declaration for `@type/react-aspect-ratio`, feel free to PR to https://github.com/DefinitelyTyped/DefinitelyTyped :)

**Comment by roderickhsiao** [comment]
https://github.com/roderickhsiao/react-aspect-ratio/releases/tag/1.0.44
