### ISSUE TITLE
nextRatio is undefined

### ISSUE THREAD

**Issue by kesla** [roderickhsiao/react-aspect-ratio#4]
Hey, thanks for this component!

When running the latest version of this in preact, I get an error on https://github.com/roderickhsiao/react-aspect-ratio/blob/master/src/index.js#L53 - the variable isn't verified?

**Comment by tinder-rhsiao** [comment]
good catch!

**Comment by roderickhsiao** [comment]
Thanks, should be fixed in 1.0.29
