### ISSUE TITLE
aspect-ratio.css may get optimised away by webpack

### ISSUE THREAD

**Issue by wu-lee** [roderickhsiao/react-aspect-ratio#42]
I'm using `react-apsect-ratio` v1.0.42 in a site built with Gatsby v2.24.50

I'm finding that when deploying the web site, the `aspect-ratio.css` file is not included (although it works when in development mode). This means that the aspect-ratio is not set properly, and the styled element collapses to zero height.

Searching for solutions, I found this: https://github.com/gatsbyjs/gatsby/issues/19446

Essentially, this suggests that the CSS gets optimised away by Webpack. The work-around, which works for me, is to create a requirement for the CSS by not only importing it, but using the returned object somehow:

    import rar from 'react-aspect-ratio/aspect-ratio.css';
    console.log(rar); // work around overzealous dependency pruning

However, it says the problem stems from the consumed npm package declaring the CSS as side-effect free in `package.json`, which I see in `react-aspect-ratio`'s `package.json`:

     "sideEffects": false

Apparently, CSS should be declared to have side-effects like this:

    "sideEffects": [
        "*.css"
    ],

(As suggested on the webpack issue here: https://github.com/webpack/webpack/issues/6741#issuecomment-372720641)

Thanks for your work `react-aspect-ratio`!

**Comment by roderickhsiao** [comment]
Hi @wu-lee thanks for report! Released `1.0.43` to mark CSS as side effect.

Let me know if it works.
