### ISSUE TITLE
Can't resolve 'react-aspect-ratio'

### ISSUE THREAD

**Issue by brightsider** [roderickhsiao/react-aspect-ratio#45]
After the update package was broken

**Comment by adiwajshing** [comment]
Yeah, same issue. Is breaking my CI builds.

**Comment by roderickhsiao** [comment]
Checking now

**Comment by roderickhsiao** [comment]
1.0.46 should fixed the issue. Thanks for reporting, there is package dependencies issue break the build script

**Comment by roderickhsiao** [comment]
https://github.com/roderickhsiao/react-aspect-ratio/releases/tag/1.0.46

**Comment by adiwajshing** [comment]
Great thanks.
