### ISSUE TITLE
Images still popping in after aspect-ratio set.

### ISSUE THREAD

**Issue by jrhager84** [roderickhsiao/react-aspect-ratio#48]
I apologize for my ignorance, but do I have to explicitly send the pre-calculated aspect ratio as a prop to this? I thought passing `{1}` would preserve the ratio that shows and adjust accordingly.

**Comment by roderickhsiao** [comment]
Could you provide code example to show how you use the library and debug steps?

**Comment by jrhager84** [comment]
Is it that I'm wrapping the `<picture>` element instead of the associated `<img>` element?

```
import { AspectRatio } from 'react-aspect-ratio'

export default function Image({ alt = "decorative image", lazy = true, src, divClasses, ...rest }) {
  const imageName = src.slice(src.lastIndexOf('/'), src.lastIndexOf('.'))
  const extension = src.slice(src.lastIndexOf('.'))
  // slicing extension is for webpack compatibility
  
  return (
    <div className={divClasses} style={{ lineHeight: '0px' }}>
      <AspectRatio ratio={1} >
        <picture>
          <img src={ require(`../public/images${imageName}${extension}?webp`) } alt={alt} {...rest} />
        </picture>
      </AspectRatio>
    </div>
  )
}
```

**Comment by roderickhsiao** [comment]
@jrhager84 yes we style the direct child to fill the space. In your case here, <picture> tag using correct aspect ratio.

You could add width/height 100% to your <img> tag then it should work

**Comment by roderickhsiao** [comment]
Also, just to clarify, let's say if your image is 400 x 300, you will need to pass
```js
<AspectRatio ratio="400/300" >
</AspectRatio>
```

either using string or calculated value should both work

**Comment by jrhager84** [comment]
So I moved it to right around the `<img>` tag, but things are still popping in and I'm not sure if it's because this isn't set correctly or what. Would you mind taking a quick look at it?

https://krista-doubleday--preview-apq5vrih.web.app/

You can see it the most on the https://krista-doubleday--preview-apq5vrih.web.app/additional-resources and https://krista-doubleday--preview-apq5vrih.web.app/crisis-resources pages.

Thanks for all of your help!

**Comment by jrhager84** [comment]
> Also, just to clarify, let's say if your image is 400 x 300, you will need to pass
> 
> ```js
> <AspectRatio ratio="400/300" >
> </AspectRatio>
> ```
> 
> either using string or calculated value should both work

How does that work if the images are responsive and this is a wrapper component? Do I have to make note of all of their native dimensions to pass in as a prop?

**Comment by roderickhsiao** [comment]
@jrhager84 when you say responsive you mean you will have multiple images with **different** aspect ratio showing on the same area? This library is used for same image ratio, unless you can change the `ratio` props when your image aspect ratio changes.

If you are all using **same** image ratio just need to change the responsive (width) and maintain the aspect ratio then you can just pass the original ratio and it should work.

Set `<AspectRatio>` to be a width of your container (or max-width). I saw you are using material design grid so you can just adopt the class name and it will just take the full width of your grid and preserve the aspect ratio.

The library will _not_ automatically calculate your image aspect ratio, you will need to pass the original dimension or ratio.

**Comment by roderickhsiao** [comment]
Lets say 

```js
<div className="responsive-grid">
<AspectRatio ratio="400/300" >
</AspectRatio>
</div>
```js

you only need to add width 100% to aspect ratio component, then it will fill up your parent grid width.

**Comment by jrhager84** [comment]
The ratio of the actual image doesn't change, but some of the images have a max-height property on them with cropping. That wouldn't affect it after initial load though, correct?

I'm just not sure of an elegant way of passing the width and height of the images short of explicitly embedding them in the props of my `<Image />` component. I just thought there was a more 'automagical' way of doing it.

**Comment by roderickhsiao** [comment]
There isn't any way to automatically detect image size before image really fetched.
So yes, you will need to pass width and height to your Img component and then pass the ratio to the Aspect Ratio component

**Comment by jrhager84** [comment]
I'm only generating static files, so I should be able to just read the image files and inject the width and height of each one passing through the component as a prop.
